# Generated by Django 5.1.6 on 2025-02-24 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('device_data', models.JSONField(blank=True, default=dict)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urls.url')),
            ],
        ),
    ]
